import type { PathNodeLike, ChapterNavigationItem } from '../types'

/** 示例章节：智能建造概论（6 个节点） */
export const samplePathNodes: PathNodeLike[] = [
  {
    id: 'ch1-node-1',
    name: '智能建造的概念与内涵',
    shortName: '智能建造概念',
    order: 1,
    shapeType: 'theory',
    level: 'basic',
    nodeType: '理论',
    x: 60,
    y: 410,
    zoneId: 'ch1-zone-1',
    chapterId: 'ch1',
    resources: '视频2｜PPT1｜练习2',
    duration: '25min',
    description: '理解智能建造的基本概念、内涵和核心特征。',
    cardOffsetX: -20,
    cardOffsetY: 38,
    status: 'completed',
    mastery: 88,
    isCurrent: false,
    isRecommended: false,
    isWeak: false
  },
  {
    id: 'ch1-node-2',
    name: '智能建造发展历程与趋势',
    shortName: '发展历程',
    order: 2,
    shapeType: 'theory',
    level: 'basic',
    nodeType: '理论',
    x: 180,
    y: 360,
    zoneId: 'ch1-zone-1',
    chapterId: 'ch1',
    resources: '视频1｜资料2｜练习3',
    duration: '30min',
    description: '了解智能建造的发展历程、现状和未来趋势。',
    cardOffsetX: 20,
    cardOffsetY: 38,
    status: 'completed',
    mastery: 60,
    isCurrent: false,
    isRecommended: false,
    isWeak: false
  },
  {
    id: 'ch1-reinforce-1',
    name: '补强：智能建造概念辨析',
    shortName: '概念辨析',
    order: 2.5,
    shapeType: 'reinforce',
    level: 'reinforce',
    nodeType: '补强',
    x: 260,
    y: 335,
    zoneId: 'ch1-zone-1',
    chapterId: 'ch1',
    resources: '视频1｜练习2',
    duration: '15min',
    description: '针对智能建造概念进行辨析与巩固，确保理解正确。',
    cardOffsetX: -20,
    cardOffsetY: 38,
    status: 'not-started',
    mastery: 0,
    isCurrent: false,
    isRecommended: true,
    isWeak: false
  },
  {
    id: 'ch1-node-3',
    name: '智能建造体系架构',
    shortName: '体系架构',
    order: 3,
    shapeType: 'integrated',
    level: 'advanced',
    nodeType: '理实一体',
    x: 340,
    y: 310,
    zoneId: 'ch1-zone-2',
    chapterId: 'ch1',
    resources: '视频2｜PPT1｜资料1｜练习4',
    duration: '40min',
    description: '掌握智能建造的体系架构和关键技术框架。',
    cardOffsetX: -20,
    cardOffsetY: 38,
    status: 'in-progress',
    mastery: 52,
    isCurrent: true,
    isRecommended: false,
    isWeak: true
  },
  {
    id: 'ch1-node-4',
    name: '智能建造标准与政策',
    shortName: '标准与政策',
    order: 4,
    shapeType: 'theory',
    level: 'advanced',
    nodeType: '理论',
    x: 500,
    y: 260,
    zoneId: 'ch1-zone-2',
    chapterId: 'ch1',
    resources: 'PPT2｜资料1｜练习3',
    duration: '25min',
    description: '了解智能建造相关标准体系和政策法规。',
    cardOffsetX: 20,
    cardOffsetY: 38,
    status: 'not-started',
    mastery: 0,
    isCurrent: false,
    isRecommended: false,
    isWeak: false
  },
  {
    id: 'ch1-node-5',
    name: '智能建造人才培养',
    shortName: '人才培养',
    order: 5,
    shapeType: 'practice',
    level: 'extended',
    nodeType: '实操',
    x: 660,
    y: 200,
    zoneId: 'ch1-zone-3',
    chapterId: 'ch1',
    resources: '案例2｜练习2',
    duration: '35min',
    description: '了解智能建造人才培养体系和职业发展路径。',
    cardOffsetX: -20,
    cardOffsetY: 38,
    status: 'not-started',
    mastery: 0,
    isCurrent: false,
    isRecommended: false,
    isWeak: false
  },
  {
    id: 'ch1-node-6',
    name: '智能建造项目案例分析',
    shortName: '项目案例',
    order: 6,
    shapeType: 'practice',
    level: 'extended',
    nodeType: '实操',
    x: 820,
    y: 130,
    zoneId: 'ch1-zone-3',
    chapterId: 'ch1',
    resources: '项目挑战1｜资料2｜练习2',
    duration: '40min',
    description: '通过典型项目案例理解智能建造的实际应用。',
    cardOffsetX: 20,
    cardOffsetY: 38,
    status: 'not-started',
    mastery: 0,
    isCurrent: false,
    isRecommended: false,
    isWeak: false
  },
  {
    id: 'ch1-node-7',
    name: '智能建造核心技术概览',
    shortName: '核心技术',
    order: 7,
    shapeType: 'theory',
    level: 'extended',
    nodeType: '理论',
    x: 0,
    y: 0,
    chapterId: 'ch1',
    resources: '视频1｜PPT1',
    duration: '28min',
    description: '概览 BIM、IoT、机器人等智能建造核心技术。',
    status: 'not-started',
    mastery: 0,
  },
  {
    id: 'ch1-node-8',
    name: '数字化施工管理',
    shortName: '数字施工',
    order: 8,
    shapeType: 'integrated',
    level: 'extended',
    nodeType: '理实一体',
    x: 0,
    y: 0,
    chapterId: 'ch1',
    resources: '案例1｜练习2',
    duration: '32min',
    description: '了解数字化施工管理流程与平台应用。',
    status: 'not-started',
    mastery: 0,
  },
  {
    id: 'ch1-node-9',
    name: '绿色建造与可持续',
    shortName: '绿色建造',
    order: 9,
    shapeType: 'theory',
    level: 'extended',
    nodeType: '理论',
    x: 0,
    y: 0,
    chapterId: 'ch1',
    resources: '资料2｜练习1',
    duration: '22min',
    description: '理解绿色建造理念与可持续建造实践。',
    status: 'not-started',
    mastery: 0,
  },
  {
    id: 'ch1-node-10',
    name: '章节综合测评',
    shortName: '综合测评',
    order: 10,
    shapeType: 'practice',
    level: 'extended',
    nodeType: '实操',
    x: 0,
    y: 0,
    chapterId: 'ch1',
    resources: '测评1',
    duration: '45min',
    description: '完成本章综合测评，检验学习成果。',
    status: 'not-started',
    mastery: 0,
  }
]

export const sampleChapterList: ChapterNavigationItem[] = [
  { id: 'ch4', name: 'BIM 技术及应用', status: 'completed', nodeCount: 8 },
  { id: 'ch1', name: '智能建造概论', status: 'in-progress', nodeCount: 7 },
  { id: 'ch2', name: '智能建造关键技术', status: 'not-started', nodeCount: 22 },
  { id: 'ch3', name: '智能建造应用', status: 'not-started', nodeCount: 6 }
]

export const sampleChapterName = '智能建造概论 · 学习路径'
